import sanitizeHtml from "sanitize-html";

export function sanitizeContent(html: string): string {
  return sanitizeHtml(html, {
    allowedTags: sanitizeHtml.defaults.allowedTags.concat([
      "img",
      "iframe",
      "h1",
      "h2",
      "h3",
      "h4",
      "figure",
      "figcaption",
      "br",
      "span",
      "video",
      "table",
      "thead",
      "tbody",
      "tfoot",
      "tr",
      "th",
      "td",
      "caption",
      "col",
      "colgroup",
    ]),
    allowedAttributes: {
      ...sanitizeHtml.defaults.allowedAttributes,
      img: ["src", "alt", "style", "width", "height"],
      iframe: ["src", "style", "allow", "allowfullscreen"],
      div: ["style", "contenteditable"],
      span: ["style"],
      table: ["style", "border", "cellpadding", "cellspacing"],
      tr: ["style"],
      td: ["colspan", "rowspan", "style", "align", "valign"],
      th: ["colspan", "rowspan", "style", "align", "valign", "scope"],
      col: ["span", "style"],
      colgroup: ["span", "style"],
      "*": ["class"],
    },
    allowedStyles: {
      "*": {
        "position": [/^relative$|^absolute$/],
        "top": [/^-?\d+/],
        "left": [/^-?\d+/],
        "width": [/^\d+/],
        "height": [/^\d+/],
        "max-width": [/^\d+/],
        "padding": [/^\d+/],
        "padding-bottom": [/^\d+/],
        "overflow": [/^hidden$/],
        "margin": [/^-?\d+/],
        "border": [/^[\d.]+(px|em|rem)?\s+(solid|dashed|dotted|double|none)/, /^0$|^none$/],
        "border-color": [/^#[0-9a-fA-F]{3,8}$|^rgb/],
        "border-style": [/^(solid|dashed|dotted|double|none)$/],
        "border-width": [/^\d+/],
        "border-collapse": [/^(collapse|separate)$/],
        "border-spacing": [/^\d+/],
        "border-radius": [/^\d+/],
        "background-color": [/^#[0-9a-fA-F]{3,8}$|^rgb/],
        "color": [/^#[0-9a-fA-F]{3,8}$|^rgb/],
        "font-size": [/^\d+/],
        "font-weight": [/^\d+$|^bold$|^normal$/],
        "font-style": [/^(italic|normal|oblique)$/],
        "text-align": [/^left$|^center$|^right$|^justify$/],
        "vertical-align": [/^(top|middle|bottom|baseline)$/],
      },
    },
    allowedIframeHostnames: ["www.youtube.com", "player.vimeo.com"],
    allowedSchemes: ["http", "https", "mailto"],
    exclusiveFilter: (frame) => frame.tag === "iframe" && !frame.attribs.src,
  });
}
